=== capturemathan/ExamExperts/xml/dtd/coursedetails.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT Courses (Course)+>
<!ELEMENT Course (CourseID,CourseName)>
<!ELEMENT CourseID (#PCDATA)>
<!ELEMENT CourseName (#PCDATA)>

=== capturemathan/ExamExperts/xml/coursedetails.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE courses SYSTEM "./dtd/coursedetails.dtd">
<?xml-stylesheet type="text/xsl" href="./xsl/coursedetails.xsl"?>
<Courses>
    <Course>
        <CourseID>M.Tech</CourseID>
        <CourseName>Masters of Technology</CourseName>
    </Course>
    <Course>
        <CourseID>MS</CourseID>
        <CourseName>Masters of Science</CourseName>
    </Course>
    <Course>
        <CourseID>MBA</CourseID>
        <CourseName>Masters of Business Administration</CourseName>
    </Course>
    <Course>
        <CourseID>MA</CourseID>
        <CourseName>Masters of Arts</CourseName>
    </Course>
    <Course>
        <CourseID>M.Com</CourseID>
        <CourseName>Masters of Commerce</CourseName>
    </Course>
</Courses>
