=== capturemathan/ExamExperts/xml/dtd/exambookmarks.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT Bookmarks (Bookmark)+>

<!ELEMENT Bookmark (Email,ExamID,ExamName,Description,Totalmarks)>
<!ELEMENT Email (#PCDATA)>
<!ELEMENT ExamID (#PCDATA)>
<!ELEMENT ExamName (#PCDATA)>
<!ELEMENT Description (#PCDATA)>
<!ELEMENT Totalmarks (#PCDATA)>

=== capturemathan/ExamExperts/xml/exambookmarks.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bookmarks SYSTEM "./dtd/exambookmarks.dtd">
<?xml-stylesheet type="text/xsl" href="exambookmarks.xsl"?>
<Bookmarks>
    <Bookmark>
        <Email>msmuthu.sk@gmail.com</Email>
        <ExamID>GRE</ExamID>
        <ExamName>Graduate Record Examination</ExamName>
        <Description>The Graduate Record Examinations is a standardized test that is an admissions requirement for many graduate schools in the United States and Canada.</Description>
        <Totalmarks>340</Totalmarks>
    </Bookmark>
    <Bookmark>
        <Email>ajaypranav06@gmail.com</Email>
        <ExamID>GATE</ExamID>
        <ExamName>Graduate Aptitude Test in Engineering</ExamName>
        <Description>The Graduate Aptitude Test in Engineering (GATE) is an examination that primarily tests the comprehensive understanding of various undergraduate subjects in engineering</Description>
        <Totalmarks>100</Totalmarks>
    </Bookmark>
    <Bookmark>
        <Email>capturesmk@gmail.com</Email>
        <ExamID>GATE</ExamID>
        <ExamName>Graduate Aptitude Test in Engineering</ExamName>
        <Description>The Graduate Aptitude Test in Engineering (GATE) is an examination that primarily tests the comprehensive understanding of various undergraduate subjects in engineering</Description>
        <Totalmarks>100</Totalmarks>
    </Bookmark>
</Bookmarks>
