=== capturemathan/ExamExperts/xml/dtd/examdetails.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT Exams (Exam)+>

<!ELEMENT Exam (ExamID,ExamName,Description,Totalmarks)>
<!ELEMENT ExamID (#PCDATA)>
<!ELEMENT ExamName (#PCDATA)>
<!ELEMENT Description (#PCDATA)>
<!ELEMENT Totalmarks (#PCDATA)>

=== capturemathan/ExamExperts/xml/examdetails.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Exams SYSTEM "./dtd/examdetails.dtd">
<?xml-stylesheet type="text/xsl" href="examdetails.xsl"?>
<Exams>
    <Exam>
        <ExamID>GRE</ExamID>
        <ExamName>Graduate Record Examination</ExamName>
        <Description>The Graduate Record Examinations is a standardized test that is an admissions requirement for many graduate schools in the United States and Canada.</Description>
        <Totalmarks>340</Totalmarks>
    </Exam>
    <Exam>
        <ExamID>GATE</ExamID>
        <ExamName>Graduate Aptitude Test in Engineering</ExamName>
        <Description>The Graduate Aptitude Test in Engineering (GATE) is an examination that primarily tests the comprehensive understanding of various undergraduate subjects in engineering</Description>
        <Totalmarks>100</Totalmarks>
    </Exam>
    <Exam>
        <ExamID>IELTS</ExamID>
        <ExamName>International English Language Testing System</ExamName>
        <Description>The International English Language Testing System, or IELTS, is an international standardized test of English language proficiency for non-native English language speakers</Description>
        <Totalmarks>9</Totalmarks>
    </Exam>
    <Exam>
        <ExamID>TOEFL</ExamID>
        <ExamName>Test of English as a Foreign Language</ExamName>
        <Description>Test of English as a Foreign Language is a standardized test to measure the English language ability of non-native speakers wishing to enroll in English-speaking universities</Description>
        <Totalmarks>120</Totalmarks>
    </Exam>
</Exams>
